### ISSUE TITLE
Consistancy on API Endpoints

### ISSUE THREAD

**Issue by djotaku** [DonorDrive/PublicAPI#43] opened 2020-10-06 20:18 UTC
Dealing with a weird bug right now due to the fact that anonymous donors don't appear on the donors endpoint while they do appear on the donations endpoint. Could we have anonymous donors appear on the donors endpiont and just not have a name attribute as you do with donations?

**Comment by timmixell** [comment] 2020-10-14 02:52
@djotaku this was done by design. The challenge with anonymous donors becomes what we return. Any individual donation can be marked as anonymous, while the donor display information is deliberately public. We don't want to provide any detail that might disclose the donor if they indicated a private donation. That would mean we'd have to omit `donorID` for anonymous donors in the list (as we do in /donations), effectively treating each anonymous donation as a separate donor.

I'd love to hear more about your problem to solve and how we might be able to help. Thanks!

**Comment by djotaku** [comment] 2020-10-18 13:10
So here's how I'm currently handling anonymous donations: https://github.com/djotaku/ELDonationTracker/blob/master/eldonationtracker/donation.py

If you look at lines 79-87 - you'll see that I deal with the fact that the endpoint doesn't provide names or amounts for anonymous donations by setting the name to Anonymous and the amount to 0. This allows the user to still see that he/she got a donation. And if the anonymous donor left a message, the message can still be displayed.

I would like to do the same with Donors. But they simply don't appear on the donor endpoint. Well, the Anonymous donor wouldn't have a message. But they would have a name (which could be set to Anonymous) and an amount. I use that plus the SQL query to create a list of the top Donors. So I could have Anonymous as one of the donors with an amount. But, sure, maybe if you have an amount there then it can be traceable back and you're trying to protect privacy. It's all well and good UNLESS the participant ONLY has Anonymous donors. Like the person who filed the bug report with me that the program kept crashing for him. Turns out that since the Donor endpoint was empty it was causing issues because my program was saying:

"Hey, this guy has donations, so I should check the donor endpoint" 

and then the endpoint came back empty. So my workaround ended up having to be https://github.com/djotaku/ELDonationTracker/blob/master/eldonationtracker/participant.py on lines 240 to add the extra check of the top donor not being None. Because, again, LOGICALLY, it's absurd to have donations without donors. 

Let me know if there's anything that could meet the goal of privacy plus a more consistent output. I mean, this is potentially pretty corner-case. How many users ONLY have anonymous donors? Just so happened that the person who opened the bug report with me only had one donor AND that donor happened to be anonymous. If not, if you haven't already done so, you may wish to update the API documentation to reflect that this is a situation that can happen.

**Comment by timmixell** [comment] 2020-10-22 10:46
@djotaku thanks for the additional context! I'll take it back to the team, but I'm not sure we'll be able to accommodate this before game day 😢

**Comment by timmixell** [comment] 2021-08-17 20:28
@djotaku this is resolved in [v1.3 of the API](https://github.com/DonorDrive/PublicAPI/blob/1.3/resources/donors.md). note this is live, we're just wrapping up the additions and edits to some other parts of the docs

**Closed by timmixell** 2021-08-17 20:28 UTC
Labels: enhancement
